### ISSUE TITLE
Write some test functions

### ISSUE THREAD

**Issue by rabernat** [hscannell/ocetrac#1]
There are two main functions:
- track
- label

We need tests for these

An open question is whether we want to also test the private functions. This may help find bugs and edge cases.

**Comment by rabernat** [comment]
There are two aspects to figure out here:

1. Technically, how do tests work in reviewnb? Where do they go? How do we run them in CI?
2. Conceptually, what / how should we test? My recommendation is to make up some synthetic data, rather than using a real dataset.

How can I help with this?

**Comment by hscannell** [comment]
**Re: 1.**  fast.ai uses reviewnb for code review so it should in theory work seamlessly with nbdev. 

In nbdev the test go right in the notebook. I have an example in [00_core.ipynb](https://github.com/hscannell/ocetrac/blob/master/00_core.ipynb) after `label` is defined, which is currently commented out.

In general, `#export` at the beginning of a cell means that the code goes into the module and docs. `#hide` means it goes into neither. No annotation means it goes into the docs but not the module. 

There are a few commands to run in the repo directory to run the tests and CI. They are:
- nbdev_build_lib
- nbdev_build_docs
- nbdev_test_nbs
- nbdev_clean_nbs

You may have to install git hooks (`nbdev_install_git_hooks`) to avoid and handle conflicts.

I've started a nbdev cheat sheet [here](https://hackmd.io/@hscannell/HyGqphMov). 

**Re: 2.** We should test that labels are correctly being wrapped around the prime meridian in `_wrap_labels(labels_2D)` and that marine heatwaves don't jump across Central America in `_id(binary_images)`. Those are the biggest traps in my opinion. 

I'd really love some help parallelizing some of the functions that currently iterate over time and where ufunc doesn't work.

**Comment by rabernat** [comment]
> I'd really love some help parallelizing some of the functions that currently iterate over time and where ufunc doesn't work.

Yes, I want to help with this for sure. But I don't feel comfortable diving into that until we have tests for what is there now.

**Comment by hscannell** [comment]
Sounds good! We'll get the tests working first.
